"""empty message

Revision ID: 136d0541f65b
Revises: 8d699b8069a0
Create Date: 2024-06-01 23:57:16.029885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136d0541f65b'
down_revision = '8d699b8069a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
