"""empty message

Revision ID: 309fa1e60337
Revises: 71400e11d344
Create Date: 2024-05-06 15:56:31.303360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309fa1e60337'
down_revision = '71400e11d344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supportteam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supportteam')
    # ### end Alembic commands ###
