"""empty message

Revision ID: 407d81b99cc7
Revises: 136d0541f65b
Create Date: 2024-06-02 00:02:15.458829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407d81b99cc7'
down_revision = '136d0541f65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
