"""empty message

Revision ID: 68eba82b427a
Revises: 407d81b99cc7
Create Date: 2024-06-11 10:20:09.296589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68eba82b427a'
down_revision = '407d81b99cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cat', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('variant', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(), nullable=True))
        batch_op.drop_column('campus')
        batch_op.drop_column('dependant_3')
        batch_op.drop_column('fullname')
        batch_op.drop_column('medial_amount')
        batch_op.drop_column('staff_id')
        batch_op.drop_column('qualities')
        batch_op.drop_column('dependant_2')
        batch_op.drop_column('code')
        batch_op.drop_column('dependant_4')
        batch_op.drop_column('unique_code')
        batch_op.drop_column('clientid')
        batch_op.drop_column('reason')
        batch_op.drop_column('email')
        batch_op.drop_column('dependant_1')
        batch_op.drop_column('position')
        batch_op.drop_column('dependant_5')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dependant_5', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dependant_1', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clientid', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unique_code', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dependant_4', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dependant_2', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('qualities', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('medial_amount', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dependant_3', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campus', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('size')
        batch_op.drop_column('price')
        batch_op.drop_column('variant')
        batch_op.drop_column('desc')
        batch_op.drop_column('cat')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
