"""empty message

Revision ID: ca244e84b74d
Revises: 68eba82b427a
Create Date: 2024-06-11 11:01:46.648110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca244e84b74d'
down_revision = '68eba82b427a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_file')
    op.drop_table('groups')
    op.drop_table('budget')
    op.drop_table('work')
    op.drop_table('committee')
    op.drop_table('item')
    op.drop_table('ask')
    op.drop_table('faq')
    op.drop_table('waitlist')
    op.drop_table('studenthalls')
    op.drop_table('course')
    op.drop_table('alumni')
    op.drop_table('getfunds')
    op.drop_table('student_data')
    op.drop_table('challenge')
    op.drop_table('hospital')
    op.drop_table('logger')
    op.drop_table('supportteam')
    op.drop_table('message')
    op.drop_table('cisl')
    op.drop_table('album')
    op.drop_table('createclient')
    op.drop_table('program')
    op.drop_table('leaders')
    op.drop_table('department')
    op.drop_table('challenges')
    op.drop_table('school')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cat', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('variant', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(), nullable=True))
        batch_op.drop_column('dependant_2')
        batch_op.drop_column('unique_code')
        batch_op.drop_column('qualities')
        batch_op.drop_column('clientid')
        batch_op.drop_column('code')
        batch_op.drop_column('reason')
        batch_op.drop_column('dependant_5')
        batch_op.drop_column('dependant_3')
        batch_op.drop_column('fullname')
        batch_op.drop_column('medial_amount')
        batch_op.drop_column('staff_id')
        batch_op.drop_column('dependant_1')
        batch_op.drop_column('email')
        batch_op.drop_column('position')
        batch_op.drop_column('dependant_4')
        batch_op.drop_column('campus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('dependant_4', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('dependant_1', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('medial_amount', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('fullname', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('dependant_3', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('dependant_5', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('clientid', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('qualities', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('unique_code', sa.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('dependant_2', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('size')
        batch_op.drop_column('price')
        batch_op.drop_column('variant')
        batch_op.drop_column('desc')
        batch_op.drop_column('cat')
        batch_op.drop_column('product_name')

    op.create_table('school',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('departments', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('number', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('school', sa.VARCHAR(), nullable=True),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('director', sa.VARCHAR(), nullable=True),
    sa.Column('directress', sa.VARCHAR(), nullable=True),
    sa.Column('others', sa.VARCHAR(), nullable=True),
    sa.Column('ministries', sa.VARCHAR(), nullable=True),
    sa.Column('total_number', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('school', sa.VARCHAR(), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('createclient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('unique_code', sa.VARCHAR(length=12), nullable=True),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('image_file', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_album', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cisl',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clientid', sa.VARCHAR(), nullable=True),
    sa.Column('clientname', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('time', sa.VARCHAR(), nullable=True),
    sa.Column('incident', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('casualties', sa.VARCHAR(), nullable=True),
    sa.Column('employees', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('police', sa.VARCHAR(), nullable=True),
    sa.Column('fire_force', sa.VARCHAR(), nullable=True),
    sa.Column('claim', sa.VARCHAR(), nullable=True),
    sa.Column('cost', sa.VARCHAR(), nullable=True),
    sa.Column('name_of_contact', sa.VARCHAR(), nullable=True),
    sa.Column('contact_number', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supportteam',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('number', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('activity', sa.VARCHAR(), nullable=True),
    sa.Column('tag', sa.VARCHAR(), nullable=True),
    sa.Column('future', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('implementation', sa.VARCHAR(), nullable=True),
    sa.Column('challenges', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clientid', sa.VARCHAR(), nullable=True),
    sa.Column('clientname', sa.VARCHAR(), nullable=True),
    sa.Column('staffname', sa.VARCHAR(), nullable=True),
    sa.Column('staffunique_code', sa.VARCHAR(), nullable=True),
    sa.Column('userid', sa.VARCHAR(), nullable=True),
    sa.Column('idcard', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('patient_name', sa.VARCHAR(), nullable=True),
    sa.Column('facility', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('expense', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('task', sa.VARCHAR(), nullable=True),
    sa.Column('tag', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('studentName', sa.VARCHAR(), nullable=True),
    sa.Column('studentID', sa.VARCHAR(), nullable=True),
    sa.Column('studentnumber', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('getfunds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(), nullable=True),
    sa.Column('ministry', sa.VARCHAR(), nullable=True),
    sa.Column('program', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('telephone', sa.VARCHAR(), nullable=True),
    sa.Column('campus', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('indexnumber', sa.VARCHAR(), nullable=True),
    sa.Column('telephone', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('schools', sa.VARCHAR(), nullable=True),
    sa.Column('course', sa.VARCHAR(), nullable=True),
    sa.Column('year', sa.VARCHAR(), nullable=True),
    sa.Column('pdf_filename', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studenthalls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('studentName', sa.VARCHAR(), nullable=True),
    sa.Column('regno', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('program', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hallname', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('caption', sa.VARCHAR(), nullable=True),
    sa.Column('answers', sa.VARCHAR(), nullable=True),
    sa.Column('campus', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ask',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ask', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('nation', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('quantity', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.VARCHAR(), nullable=True),
    sa.Column('tag', sa.VARCHAR(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='ft_item_group_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hours_worked', sa.FLOAT(), nullable=False),
    sa.Column('date_completed', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('budget', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdf_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=100), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    # ### end Alembic commands ###
